name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: setup dependencies
      run: |
        sudo apt install -y build-essential ocl-icd-libopencl1 cmake git pkg-config libclang-dev clang llvm make ninja-build ocl-icd-libopencl1 ocl-icd-dev ocl-icd-opencl-dev libhwloc-dev zlib1g zlib1g-dev clinfo dialog apt-utils libtinfo-dev libgmp-dev
        curl -sSL https://get.haskellstack.org/ | sh
    
    - name: get & build Furthark
      run: |
        git clone https://github.com/diku-dk/futhark
        cd futhark
        stack setup
        stack build
        stack install
        
    - name: get & build PoCL
      run: |
        git clone https://github.com/pocl/pocl.git
        mkdir pocl-build && cd pocl-build
        cmake ../pocl
        make -j4 install
